#!/usr/bin/env python
from sidewinder import sendsocket, recvsocket
import socket
import os
import time
import logging
import tempfile

logging.basicConfig(level=logging.DEBUG)

def child(channel):
    i = 1
    while True:
        fd, path = tempfile.mkstemp()
        logging.debug('Sending socket: %d' % fd)
        r = sendsocket(channel, fd)
        logging.debug('%09d Returned: %r' % (i, r))
        os.close(fd)
        i += 1


def parent(channel):
    i = 1
    while True:
        x = recvsocket(channel)
        logging.debug('%09d Recv\'d %d' % (i, x))
        os.close(x)
        i += 1


def main():
    fd1, fd2 = socket.socketpair()
    logging.debug('UNIX socket pair: %r %r', fd1, fd2)
    pid = os.fork()
    if pid == 0:
        fd2.close()
        child(fd1)
    elif pid > 0:
        fd1.close()
        logging.debug('Close child.')
        parent(fd2)
    else:
        logging.error('Fork error')


if __name__ == '__main__':
    main()
